import { TARGET_BY_ID } from "@/data/agentsV2";
import { AGENT_JSON_PATH } from "@/data/agentJsonSchema";
import { preflight } from "./preflight";

/**
 * A release, as data.
 *
 * Same shape as an authoring run — an ordered array of typed plain-data events
 * walked one per tick — with one property that carries the whole safety story:
 *
 *   THE COMMIT EVENT EXISTS, OR IT DOES NOT.
 *
 * Whether the release is allowed is decided here, at compile time, by a pure
 * function of the record. A blocked release compiles an array with no `commit`
 * in it at all, so "nothing was written" is a decidable property of the data
 * rather than a promise about the order things happen in. There is no rollback
 * because there was never a forward path, and no window in which a version has
 * been taken but a package has not.
 *
 * The version is taken at the commit and nowhere else. A version bumped before
 * the checks finish is a lie the moment one fails: releases are immutable, so
 * a number that was handed out and then withdrawn was never immutable.
 */

export const RELEASE_BEAT = {
  think: 520,
  check: 260,
  commit: 360,
  target: 200,
  halt: 0,
  done: 0,
};

export const beatOfRelease = (ev) => RELEASE_BEAT[ev?.t] ?? 200;

/* ── events ──────────────────────────────────────────────────────────────── */

const think = (label) => ({ t: "think", label });
const check = (c) => ({ t: "check", ...c });
const commit = (plan) => ({ t: "commit", ...plan });
const target = (id, path) => ({ t: "target", id, path });
const halt = (text) => ({ t: "halt", text });
const done = (text) => ({ t: "done", text });

/**
 * Compile a release for this record and these options.
 *
 * @param {object} agent
 * @param {{kind: string, notes: string, targets: string[], version: string}} plan
 */
export function compileRelease(agent, plan) {
  const report = preflight(agent);
  const blocked = report.errors.length > 0;

  const out = [
    think(`reading the folder — ${agent.files.length} files, ${report.checks.length} checks`),
    ...report.checks.map(check),
  ];

  if (blocked) {
    out.push(
      halt(
        `Stopped before taking a version. Nothing was written: ${
          agent.release ? `v${agent.release.version} is still current` : "this agent is still unreleased"
        }, and the folder is unchanged.`,
      ),
    );
    return out;
  }

  out.push(commit(plan));

  // Rendered after the commit because they are a description of what was just
  // recorded, not a sequence of things happening on someone's machine.
  for (const id of plan.targets) {
    const t = TARGET_BY_ID[id];
    if (t) out.push(target(id, `${t.path}${agent.slug}/`));
  }

  out.push(
    done(
      `Recorded as v${plan.version}. The bytes stay in this browser — Aziron has no installer in this prototype, so a release here is a version, a target list and a file manifest, and nothing else.`,
    ),
  );

  return out;
}

/* ── the transcript reducer ──────────────────────────────────────────────── */

export const EMPTY_RELEASE = { think: null, checks: [], targets: [], committed: null, halted: null, done: null };

export function reduceRelease(state, ev) {
  switch (ev.t) {
    case "think":
      return { ...state, think: ev.label };
    case "check":
      return { ...state, think: null, checks: [...state.checks, ev] };
    case "commit":
      return { ...state, think: null, committed: ev };
    case "target":
      return { ...state, targets: [...state.targets, ev] };
    case "halt":
      return { ...state, think: null, halted: ev.text };
    case "refused":
      // Player-emitted, never planned: the record moved while the checks ran.
      return { ...state, think: null, halted: ev.text };
    case "done":
      return { ...state, done: ev.text };
    default:
      return state;
  }
}

/**
 * The file list a release records, with each file's size.
 *
 * Computed from the projection AFTER the commit, because the config file is
 * regenerated by the release itself — its version line changes, so a manifest
 * taken a moment earlier disagrees with the package it claims to describe.
 */
export const manifestOf = (files) =>
  [...files]
    .map((f) => ({ path: f.path, chars: f.content.length }))
    .sort((x, y) => x.path.localeCompare(y.path));

export const manifestChars = (m) => m.reduce((s, f) => s + f.chars, 0);

export { AGENT_JSON_PATH };
